name: MI A1
on:
  workflow_dispatch:
jobs:
  build:

    name: Build Kernel for Xiaomi Mi A1 (tissot)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Cleanup Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 libstdc++6 rsync perl

    - name: Setup Cache (ccache)
      uses: actions/cache@v5
      with:
        path: ~/.cache/ccache_mia1
        key: kernel-ccache-tissot-build-mia1.sh-${{ github.run_id }}
        restore-keys: |
          kernel-ccache-tissot-build-mia1.sh-
          kernel-ccache-tissot-
          kernel-ccache-

    - name: Build Kernel
      run: |
        chmod +x mia1.sh
        echo "Using mia1.sh....."
        bash mia1.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: LightningKernel-tissot
        path: ./*.zip
        if-no-files-found: error
